regions:
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  - af-south-1
  - ap-east-1
  - ap-northeast-1
  - ap-northeast-2
  - ap-northeast-3
  - ap-south-1
  - ap-south-2
  - ap-southeast-1
  - ap-southeast-2
  - ap-southeast-3
  - ap-southeast-4
  - ca-central-1
  - ca-west-1
  - eu-central-1
  - eu-central-2
  - eu-north-1
  - eu-south-1
  - eu-south-2
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - il-central-1
  - me-central-1
  - me-south-1
  - sa-east-1
  - global

account-blocklist:
  - "999999999999" # Example blocked account

# ðŸ”’ Safe guard: Exclude all IAM resources globally
resource-types:
  excludes:
    - IAMUser
    - IAMRole
    - IAMRolePolicy
    - IAMUserPolicy
    - IAMPolicy
    - IAMInstanceProfile
    - IAMRolePolicyAttachment
    - IAMUserPolicyAttachment
    - IAMGroupPolicyAttachment
    - IAMUserGroupAttachment
    - IAMGroup
    - IAMAccessKey
    - IAMAccountAlias
    - IAMAccountPasswordPolicy
    - IAMAccountSummary
    - IAMLoginProfile
    - IAMOpenIDConnectProvider
    - IAMSAMLProvider
    - IAMServerCertificate
    - IAMServiceLinkedRole
    - IAMServiceSpecificCredential
    - IAMSigningCertificate
    - IAMSSHPublicKey
    - IAMVirtualMFADevice
    - IAMUserAccessKey
    - IAMUserGroupMembership
    - IAMUserSSHKey

accounts:
  "AWS_ACCOUNT_ID_PLACEHOLDER":
    filters:
      __global__:
        - property: "tag:NUKE_RETAIN"
          value: "true"

      S3Bucket:
        # Skip buckets starting with iac-rlhf
        - type: contains
          value: "iac-rlhf"
        - type: regex
          value: "^iac-rlhf.*"

      S3Object:
        # Skip objects inside those buckets
        - property: "Bucket"
          type: regex
          value: "^iac-rlhf.*"

      S3BucketPolicy:
        # Skip policies for those buckets
        - property: "BucketName"
          type: regex
          value: "^iac-rlhf.*"

      S3BucketAcl:
        # Skip ACLs for those buckets
        - property: "BucketName"
          type: regex
          value: "^iac-rlhf.*"
